Repository klaframboise/Treeflow.js, pull requests merged in 2020-03, with the labels that each got.

#9 4-Progressed in vulnerable package upgrade - 5 left, webpack can compile
  lib/Components/index.js
  package.json
  utils/Default.json
  utils/WebpackGenerator.js
Labels: enhancement

#12 Upgraded React and MobX
  lib/Components/FormItem/index.js
  lib/Components/FormSet.js
  lib/Components/Panel.js
  lib/Components/Table/Plain.js
  lib/Echarts/Echarts.js
  utils/Default.json
Labels: enhancement

#14 Fixed styling issues due to upgrade
  utils/WebpackGenerator.js
Labels: bug

#16 Updated to Echarts 4
  .gitignore
  utils/Default.json
Labels: enhancement

#15 13 move previous readme to wiki
  README.md
Labels: documentation
