Repository klaframboise/Treeflow.js, pull requests merged in 2020-12, with the labels that each got.

#33 Implemented historyLength and count mode for bin chart
  doc/Samples/10.Pre-Clustered-Bubble-Chart/Data-mocker.js
  doc/Samples/11.Count-Bubble-Chart/Data-mocker.js
  doc/Samples/12.Bubble-Chart-history-length/Data-mocker.js
  doc/Samples/13.Bubble-Chart-transition-period/Data-mocker.js
  doc/Samples/14.Average-Bubble-Chart/Data-mocker.js
  doc/Samples/15.Bin-Chart-Count/Data-mocker.js
  lib/histogram/histogram.js
  utils/EchartAdaptor.js
  utils/NodeGenerator.js
  utils/PageGenerator.js
  utils/StoreGenerator.js
  utils/code-blocks/binHistoryLengthInterval.js
  utils/code-blocks/bubbleHistoryLengthInterval.js
Labels: enhancement

#30 Implemented bin chart and added it in compiler.
  README.md
  doc/Samples/10.Pre-Clustered-Bubble-Chart/Data-mocker.js
  doc/Samples/11.Count-Bubble-Chart/Data-mocker.js
  doc/Samples/12.Bubble-Chart-history-length/Data-mocker.js
  doc/Samples/13.Bubble-Chart-transition-period/Data-mocker.js
  doc/Samples/14.Average-Bubble-Chart/Data-mocker.js
  doc/Samples/15.Bin-Chart-Count/Config.json
  doc/Samples/15.Bin-Chart-Count/Data-mocker.js
  lib/histogram/histogram.js
  lib/histogram/utils.js
  lib/histogram/utils/array.js
  lib/histogram/utils/dataProcess.js
  lib/histogram/utils/number.js
  lib/histogram/utils/object.js
  lib/histogram/utils/range.js
  lib/histogram/utils/tickStep.js
  package.json
  utils/Default.json
  utils/EchartAdaptor.js
  utils/NodeGenerator.js
  utils/PageGenerator.js
  utils/StoreGenerator.js
  utils/code-blocks/binHistoryLengthInterval.js
  utils/code-blocks/bubbleHistoryLengthInterval.js
Labels: enhancement

#36 Added fix for reported bug in line graph
  utils/StoreGenerator.js
Labels: bug

#38 Fixed logical bug with count mode implementation for bin chart
  lib/histogram/histogram.js
Labels: bug

#40 Added customization options for user for current bin chart implementation
  README.md
  doc/Samples/15.Bin-Chart-Count/Config.json
  doc/Samples/16.Bin-Chart-Average/Config.json
  package.json
  utils/EchartAdaptor.js
  utils/StoreGenerator.js
  utils/code-blocks/binHistoryLengthInterval.js
Labels: enhancement

#43 42 Exposed clustering hyperparameter configuration in compiler
  doc/Samples/11.Count-Bubble-Chart/Config.json
  doc/Samples/12.Bubble-Chart-history-length/Config.json
  doc/Samples/13.Bubble-Chart-transition-period/Config.json
  doc/Samples/14.Average-Bubble-Chart/Config.json
  doc/Samples/15.Bin-Chart-Count/Config.json
  utils/StoreGenerator.js
Labels: enhancement

#44 Added bin chart gifs to doc
  doc/bin-chart-average-mode.gif
  doc/bin-chart-count-mode.gif
Labels: documentation
